code --install-extension abusaidm.html-snippets
code --install-extension akamud.vscode-javascript-snippet-pack
code --install-extension alefragnani.Bookmarks
code --install-extension alexdima.copy-relative-path
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension burkeholland.simple-react-snippets
code --install-extension chenxsan.vscode-standardjs
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension codepunkt.vscode-javascript-snippets
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.jquerysnippets
code --install-extension DryWolf.dark-plus-plus-theme
code --install-extension dssiqueira.drupal-8-snippets
code --install-extension ecmel.vscode-html-css
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension fknop.vscode-npm
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension golf1052.code-sync
code --install-extension hdg.live-html-previewer
code --install-extension hollowtree.vue-snippets
code --install-extension HookyQR.beautify
code --install-extension Hridoy.jquery-snippets
code --install-extension HvyIndustries.crane
code --install-extension igorming.useful-react-snippets
code --install-extension ikappas.composer
code --install-extension ionutvmi.path-autocomplete
code --install-extension jasonnutter.search-node-modules
code --install-extension jawandarajbir.react-vscode-extension-pack
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension ms-vsts.team
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension nathanchapman.JavaScriptSnippets
code --install-extension octref.vetur
code --install-extension ritwickdey.live-sass
code --install-extension ritwickdey.LiveServer
code --install-extension robinbentley.sass-indented
code --install-extension sdras.vue-vscode-extensionpack
code --install-extension sdras.vue-vscode-snippets
code --install-extension Shan.code-settings-sync
code --install-extension sledsworth.react-redux-es6-snippets
code --install-extension steoates.autoimport
code --install-extension thanhtrang.vscode-react-redux-snippets
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension WallabyJs.quokka-vscode
code --install-extension whizkydee.material-palenight-theme
code --install-extension wmaurer.vscode-jumpy
code --install-extension xabikos.JavaScriptSnippets
code --install-extension xabikos.ReactSnippets
